
services:
  flask_app:
    container_name: flask_app
    image: debasishray/satxtract-backend:v2.1
    build: Back-End
    ports:
      - "5000:5000"
    networks:
      - satxtract-net
    volumes:
      - ./uploads:/app/uploads
      - ./prediction:/app/prediction
      - ./models:/app/models  # Mount the host's 'models' directory to '/app/models' in the container
    

  nextjs_app:
    container_name: nextjs_app
    image: debasishray/satxtract-frontend:v2.1
    build: Front-End
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://flask_app:5000  # Set the API URL for Flask backend
    depends_on:
      - flask_app
    networks:
      - satxtract-net
    env_file:
      - .env.docker  

networks:
  satxtract-net:
    driver: bridge
