FROM python:3.11-slim

WORKDIR /app

# Install necessary system packages
RUN apt-get update && \
    apt-get install -y \
    python3-venv \
    build-essential \
    python3-dev \
    libatlas-base-dev \
    && rm -rf /var/lib/apt/lists/*


RUN apt-get update && apt-get install -y libgl1
RUN apt-get update && apt-get install -y libglib2.0-0 libsm6 libxrender1 libxext6



# Copy all project files
COPY . /app

# Copy the Earth Engine service account key
# COPY key.json /app/key.json

# Create a virtual environment
RUN python3 -m venv /app/osgeo_env

# Install Python dependencies inside the virtual environment
RUN /app/osgeo_env/bin/pip install --upgrade pip setuptools wheel && \
    /app/osgeo_env/bin/pip install --no-cache-dir --upgrade -r requirements.txt

# Set environment variables
ENV osgeo_env=/app/osgeo_env
ENV PATH="$osgeo_env/bin:$PATH"
# ENV GOOGLE_APPLICATION_CREDENTIALS="/app/key.json"


EXPOSE 5000

# Run the app
CMD ["python", "receiveWebData.py", "--host=0.0.0.0", "--port=5000"]